### ISSUE TITLE
Radial Bound Error and PTO1.xtl missing

### ISSUE THREAD

**Issue by XiaoWang-Github** [HamishGBrown/py_multislice#5]
PTO1.xtl is missing in the demo PTO_potential.ipynb.
Test.py cannot run and has the following run-time error

..............RadialBound: No. nodes changed in iteration 421 0 2 1
Error occured in RadialSolver, -6
2 1 -4.808E-01

**Comment by drdingpeng** [comment]
Hi Xiaowang,

That is because of the error in PFAC function. You may need to install the FAC lib correctly.
